version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: stat,ruok,conf,isro
    restart: always
  kafka:
    image: confluentinc/cp-kafka:6.2.2
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_SEGMENT_BYTES: 16777216
      KAFKA_LOG_RETENTION_BYTES: 134217728
    restart: always
  schemaregistry:
    image: confluentinc/cp-schema-registry:6.2.2
    hostname: schemaregistry
    container_name: schemaregistry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: "schemaregistry"
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: "full"
      # SCHEMA_REGISTRY_DEBUG: 'true'
    restart: always
  restproxy:
    image: confluentinc/cp-kafka-rest:6.2.2
    hostname: restproxy
    container_name: restproxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schemaregistry:8081/
      KAFKA_REST_HOST_NAME: "restproxy"
    depends_on:
      - schemaregistry
    restart: always
# Uncomment this for the schemaregistry ui and kafkatopics ui
  schemaregistryui:
    image: landoop/schema-registry-ui
    hostname: schemaregistryui
    container_name: schemaregistryui
    ports:
      - "8083:8083"
    environment:
      SCHEMAREGISTRY_URL: http://schemaregistry:8081
      PROXY: "TRUE"
      ALLOW_GLOBAL: "1"
      ALLOW_DELETION: "1"
      ALLOW_TRANSITIVE: "1"
      PORT: 8083
    depends_on:
      - schemaregistry
    restart: always
  kafkatopicsui:
    image: landoop/kafka-topics-ui:latest
    hostname: kafkatopicsui
    container_name: kafkatopicsui
    depends_on:
      - restproxy
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: http://restproxy:8082
      PROXY: "TRUE"
    restart: always
